# Generated by Django 5.1.7 on 2025-03-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
