# Generated by Django 5.1.7 on 2025-03-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_alter_urldata_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
