# Generated by Django 5.1.7 on 2025-03-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0004_alter_urldata_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='slug',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
